import { useQuery } from "@apollo/client";
import { GetStaticProps } from "next";
import Head from "next/head";
import { ReactElement, useEffect, useState } from "react";
import { InitialPeople } from "../components/PeopleOverview";
import { client } from "../graphql/client";
import {
  GET_INITIAL_PEOPLE,
  GET_PEOPLE_DETAILS,
} from "../graphql/queries/getInitialPeople";

export default function Home({ peopleData }): ReactElement {
  console.log(peopleData);

  // TODO Future testing will define getStaticPaths or other dynamic data fetching

  const { error, data, loading } = useQuery(GET_PEOPLE_DETAILS, {
    client: client,
  });

  console.log(data);

  return (
    <>
      <Head>
        <title>Ravn Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="bg-ravn-black text-white py-4 px-10">
        <h1 className="font-bold text-2xl ">Ravn Star Wars Registry</h1>
      </header>

      <main className="flex">
        {/* //* Assumed the expected element's responsive width */}
        <div className="border-r-2 h-screen w-full sm:max-w-[50%] md:max-w-[30%]">
          {peopleData.map((r) => (
            <div key={r.id} className="hover:bg-gray-100 cursor-pointer">
              <InitialPeople peopleData={r} />
            </div>
          ))}
        </div>
        <div className="hidden sm:block">{/* Details Page */}</div>
      </main>
    </>
  );
}

/* 
  * Using NextJs built-in functionality data-fetching
  ? Next requires this function to be on the same page as where the data will be used
*/

export const getStaticProps: GetStaticProps = async () => {
  // * Getting the first 5 people to be already rendered beforehand
  const { data } = await client.query({
    query: GET_INITIAL_PEOPLE,
  });

  if (!data)
    return {
      notFound: true,
    };

  return {
    props: {
      peopleData: data.allPeople.people,
    },
  };
};
