import { ApolloClient, gql, InMemoryCache } from "@apollo/client";
import { GetStaticProps, NextPageContext } from "next";
import Head from "next/head";
import Image from "next/image";
import { ReactElement } from "react";

export default function Home({ peopleData }): ReactElement {
  console.log(peopleData);
  return (
    <>
      <Head>
        <title>Ravn Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="font-bold text-2xl bg-black text-white p-4">
        Ravn Star Wars Registry
      </h1>

      <main className="flex flex-col">
        <div>
          {peopleData.map((p) => (
            <div key={p.id}>
              <li>{p.name}</li>
            </div>
          ))}
        </div>
      </main>
    </>
  );
}

/* 
  * Using NextJs built-in functionality data-fetching
  ? Next requires this function to be on the same page as where the data will be used
*/
export const getStaticProps: GetStaticProps = async (ctx) => {
  const client = new ApolloClient({
    uri: "https://swapi-graphql.netlify.app/.netlify/functions/index/",
    cache: new InMemoryCache(),
  });

  // * Getting the first 5 people
  const { data } = await client.query({
    query: gql`
      query allPeople {
        allPeople(first: 5) {
          people {
            name
            eyeColor
            birthYear
            id
          }
        }
      }
    `,
  });

  return {
    props: {
      peopleData: data.allPeople.people,
    },
  };
};
